# Generated by Django 4.0.2 on 2022-02-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=32)),
                ('tax_number', models.PositiveIntegerField(default=99999999999, primary_key=True, serialize=False, unique=True)),
                ('street', models.CharField(max_length=32)),
                ('house_number', models.SmallIntegerField()),
                ('flat_number', models.SmallIntegerField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default='2022-02-18')),
            ],
        ),
    ]
