# Generated by Django 4.0.2 on 2022-02-18 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=32)),
                ('tax_number', models.PositiveIntegerField(default=99999999999, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=32)),
                ('house_number', models.SmallIntegerField()),
                ('flat_number', models.SmallIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('contractor_tax_number', models.PositiveIntegerField(default=99999999999)),
                ('opis', models.TextField(default='')),
                ('issue_date', models.DateField(default=datetime.datetime(2022, 2, 18, 16, 21, 57, 131924), null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('plakat', models.ImageField(blank=True, null=True, upload_to='plakaty')),
            ],
        ),
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(default=0)),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (1, 'Horror'), (0, 'Inne'), (2, 'Komedia'), (4, 'Drama')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recenzja', models.TextField(blank=True, default='')),
                ('gwiazdki', models.PositiveSmallIntegerField(default=5)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicesweb.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='dodatkowe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicesweb.moreinfo'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('invoices', models.ManyToManyField(related_name='actors', to='invoicesweb.Invoice')),
            ],
        ),
    ]
