# Generated by Django 4.0.2 on 2022-02-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePosition',
            fields=[
                ('product_or_service', models.TextField(primary_key=True, serialize=False)),
                ('unit', models.CharField(choices=[(0, 'pcs.'), (1, 'serv.'), (2, 'm'), (3, 'l'), (4, 'kg')], default=0, max_length=1)),
                ('price_per_unit_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('total_price_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tax_rate', models.CharField(choices=[(0, 0.23), (1, 0.08), (2, 0.05), (3, 0.0), (4, 'free')], default=0.23, max_length=1)),
                ('total_price_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
