# Generated by Django 4.0.2 on 2022-02-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contractor_tax_number',
            field=models.CharField(default=1, max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=1, max_length=32),
        ),
    ]
