# Generated by Django 3.0.4 on 2020-03-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesweb', '0002_auto_20200307_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='opis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='plakat',
            field=models.ImageField(blank=True, null=True, upload_to='plakaty'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='premiera',
            field=models.DateField(blank=True, null=True),
        ),
    ]
