# Generated by Django 4.0.2 on 2022-02-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesweb', '0002_invoiceposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceposition',
            name='product_or_service',
            field=models.TextField(default='flower', primary_key=True, serialize=False),
        ),
    ]
