# Generated by Django 4.0.2 on 2022-02-16 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesweb', '0006_auto_20200327_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='more',
        ),
        migrations.AddField(
            model_name='invoice',
            name='dodatkowe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicesweb.moreinfo'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='invoices',
            field=models.ManyToManyField(related_name='actors', to='invoicesweb.Invoice'),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (0, 'Inne'), (2, 'Komedia'), (4, 'Drama'), (1, 'Horror')], default=0),
        ),
    ]
