# Generated by Django 4.0.2 on 2022-02-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicesweb', '0007_remove_invoice_more_invoice_dodatkowe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tytul',
            new_name='invoice_number',
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (0, 'Inne'), (1, 'Horror'), (2, 'Komedia'), (3, 'Sci-fi')], default=0),
        ),
    ]
